=== boSun007/myTest/json/booking/request/schema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
    "type": "object",
    "properties": {
        "arrival": {
            "type": "string",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
            "description": "The arrival date"
        },
        "departure": {
            "type": "string",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
            "description": "The departure date"
        },
        "roomallocation": {
            "type": "integer",
            "description": "The amount of rooms required",
            "minimum": 1
        },
        "guestcounts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "enum": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            18,
                            19
                        ]
                    },
                    "count": {
                        "type": "integer"
                    }
                },
                "required": [
                    "code",
                    "count"
                ],
                "additionalProperties": false,
                "uniqueItems": true
            },
            "minItems": 1,
            "uniqueItems": true,
            "description": "The number of guests (per room) according to each specific OTA Age Qualifying Code (AQC). The following AQCs are supported: 1 (Over 21), 2 (Over 65), 3 (Under 2), 4 (Under 12), 5 (Under 17), 6 (Under 21), 7 (Infant), 8 (Child), 9 (Teenager), 10 (Adult), 11 (Senior), 18 (Under 10), 19 (Junior)"
        },
        "promotion": {
            "type": [
                "string",
                "null"
            ],
            "description": "Promotion code"
        },
        "group": {
            "type": [
                "string",
                "null"
            ],
            "description": "Group or block code"
        },
        "room": {
            "type": "string",
            "description": "Room type"
        },
        "rate": {
            "type": "string",
            "description": "Rate plan"
        },
        "guest": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Lookup valid titles by using the '\/information\/titles\/<property>' resource"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "address": {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "home",
                                "work",
                                "postal"
                            ]
                        },
                        "city": {
                            "type": "string"
                        },
                        "country": {
                            "type": "string",
                            "description": "Lookup valid country codes by using the '\/information\/countries\/<property>' resource"
                        },
                        "lines": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "minItems": 1
                        },
                        "postcode": {
                            "type": "string"
                        },
                        "region": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "type",
                        "country"
                    ]
                },
                "contacts": {
                    "type": "object",
                    "properties": {
                        "emails": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "enum": [
                                            "email"
                                        ]
                                    },
                                    "address": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type",
                                    "address"
                                ]
                            },
                            "minItems": 1,
                            "uniqueItems": true
                        },
                        "phones": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "enum": [
                                            "phone",
                                            "mobile",
                                            "fax",
                                            "home"
                                        ]
                                    },
                                    "number": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type",
                                    "number"
                                ]
                            },
                            "minItems": 1,
                            "uniqueItems": true
                        }
                    },
                    "required": []
                }
            },
            "required": [
                "firstname",
                "lastname",
                "title"
            ]
        },
        "reference": {
            "type": "object",
            "description": "The booking reference number for external and third party systems",
            "properties": {
                "number": {
                    "type": "string",
                    "description": "The external reference number"
                },
                "type": {
                    "type": "string",
                    "description": "The external reference type"
                }
            },
            "required": [
                "number"
            ]
        },
        "comments": {
            "type": "object",
            "properties": {
                "private": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1
                },
                "public": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1
                }
            },
            "required": []
        },
        "payment": {
            "type": "object",
            "properties": {
                "creditcard": {
                    "type": "object",
                    "description": "Required when securing the booking via credit card",
                    "properties": {
                        "type": {
                            "type": "string",
                            "description": "Lookup valid credit card type codes by using the '\/information\/creditcards\/<property>' service"
                        },
                        "number": {
                            "type": "string",
                            "description": "Credit card number"
                        },
                        "holder": {
                            "type": "string",
                            "description": "Credit card holder's name as it appears on the credit card"
                        },
                        "expiry": {
                            "type": "string",
                            "pattern": "^[0-9]{2}\/[0-9]{4}$",
                            "description": "Credit card expiration date"
                        }
                    },
                    "required": [
                        "type",
                        "number",
                        "holder",
                        "expiry"
                    ]
                }
            },
            "required": []
        },
        "fields": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": [
                            "date",
                            "number",
                            "string"
                        ]
                    },
                    "name": {
                        "type": "string"
                    },
                    "value": {
                        "type": "string"
                    }
                },
                "required": [
                    "type",
                    "name",
                    "value"
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "roomrates": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "date": {
                        "type": "string",
                        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
                    },
                    "base": {
                        "type": "number"
                    }
                },
                "required": [
                    "date",
                    "base"
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": [
        "arrival",
        "departure",
        "roomallocation",
        "guestcounts",
        "room",
        "rate",
        "guest"
    ]
}

=== boSun007/myTest/json/booking/request/fullJson.json
{
    "arrival": "2935-20-62",
    "departure": "9985-14-59",
    "roomallocation": 115,
    "guestcounts": [
      {
        "code": 18,
        "count": 4
      }
    ],
    "room": "ABCDEFGHIJKLMNOPQR",
    "rate": "ABCDEFGHIJKLMNOPQRSTU",
    "guest": {
      "firstname": "ABCDEF",
      "lastname": "ABCDEFGHIJKLMNOPQRSTUVWXYZAB",
      "title": "ABCDEFGHIJ",
      "address": {
        "type": "postal",
        "country": "ABCDEFGHIJKL",
        "city": "ABCDEFGHIJKL",
        "lines": [
          "ABCDEFGHIJKLMNOPQRSTU"
        ],
        "postcode": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        "region": "ABCDEFGHIJK"
      },
      "contacts": {
        "emails": [
          {
            "type": "email",
            "address": "ABCDEFGH"
          }
        ],
        "phones": [
          {
            "type": "phone",
            "number": "ABCDEFGHIJKLMNOPQR"
          }
        ]
      }
    },
    "promotion": null,
    "group": null,
    "reference": {
      "number": "ABCDEFGHIJKLMNOPQR",
      "type": "ABCDEFGHIJKLMNOPQRSTU"
    },
    "comments": {
      "private": [
        "ABCDEFGHIJKLMNOPQRSTUVWXY"
      ],
      "public": [
        "ABCDEFGHIJ"
      ]
    },
    "payment": {
      "creditcard": {
        "type": "ABCDEFGHIJKLMNOPQRSTUVWX",
        "number": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
        "holder": "ABCDEFGHIJKLMNOPQRSTUV",
        "expiry": "14/8952"
      }
    },
    "fields": [
      {
        "type": "date",
        "name": "ABCDEFGHIJKLMNOPQRSTUVWX3212",
        "value": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC1"
      },
      {
        "type": "date",
        "name": "ABCDEFGHIJKLMNOPQRSTUVWX31232122",
        "value": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC111"
      }
    ],
    "roomrates": [
      {
        "date": "0119-18-51",
        "base": 869.75
      }
    ]
  }

=== boSun007/myTest/json/booking/request/json.json
{
    "arrival": "2013-11-07",
    "departure": "2013-11-09",
    "guestcounts": [
        {
            "code": 10,
            "count": 1
        }
    ],
    "room": "SUIT",
    "rate": "BAR",
    "roomallocation": 1,
    "promotion": null,
    "guest": {
        "title": "Mr",
        "firstname": "John",
        "lastname": "Smith",
        "address": {
            "type": "postal",
            "lines": [
                "123 Long street",
                "Green Pastures"
            ],
            "city": "Cape Town",
            "region": "Western Cape",
            "country": "ZA",
            "postcode": "1234"
        },
        "contacts": {
            "phones": [
                {
                    "type": "phone",
                    "number": "1234567890"
                },
                {
                    "type": "phone",
                    "number": "22222222222"
                },
                {
                    "type": "mobile",
                    "number": "0820822082"
                }
            ],
            "emails": [
                {
                    "type": "email",
                    "address": "test@example.com"
                },
                {
                    "type": "email",
                    "address": "test2@example.com"
                }
            ]
        }
    },
    "comments": {
        "public": [
            "A first public comment",
            "A second public comment"
        ],
        "private": [
            "A private comment"
        ]
    }
}
