=== boSun007/myTest/json/roomAvailablilityCheck/response/schema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
    "type": "object",
    "properties": {
        "property": {
            "type": "string",
            "description": "The property code"
        },
        "propertyname": {
            "type": "string",
            "description": "The property name"
        },
        "arrival": {
            "type": "string",
            "description": "The arrival date"
        },
        "departure": {
            "type": "string",
            "description": "The departure date"
        },
        "nights": {
            "type": "integer",
            "description": "The amount of nights",
            "minimum": 1
        },
        "roomallocation": {
            "type": "integer",
            "description": "The amount of rooms required",
            "minimum": 1
        },
        "guestcounts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "enum": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            18,
                            19
                        ]
                    },
                    "count": {
                        "type": "integer"
                    }
                },
                "required": [
                    "code",
                    "count"
                ],
                "additionalProperties": false,
                "uniqueItems": true
            },
            "minItems": 1,
            "uniqueItems": true,
            "description": "The number of guests (per room) according to each specific OTA Age Qualifying Code (AQC)"
        },
        "promotion": {
            "type": [
                "string",
                "null"
            ],
            "description": "Promotion code"
        },
        "group": {
            "type": [
                "string",
                "null"
            ],
            "description": "Group or block code"
        },
        "trace": {
            "type": "string",
            "description": "Unique response identifier"
        },
        "available": {
            "type": "boolean",
            "description": "Whether one or more rooms are available"
        },
        "rooms": {
            "type": "array",
            "description": "A list of room types",
            "items": {
                "type": "object",
                "required": [
                    "code",
                    "name",
                    "availability"
                ],
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "availability": {
                        "type": "integer",
                        "minimum": 0
                    }
                }
            },
            "minItems": 1
        },
        "rates": {
            "type": "array",
            "description": "A list of rate plans",
            "items": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "depositrequired": {
                        "type": "boolean",
                        "description": "Mandatory deposit"
                    },
                    "deposit": {
                        "type": "object",
                        "properties": {
                            "amount": {
                                "type": "number"
                            },
                            "date": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "date"
                        ]
                    },
                    "category": {
                        "type": "string"
                    },
                    "cancel": {
                        "type": "object",
                        "properties": {
                            "date": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "date"
                        ]
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "required": [
                    "code",
                    "name"
                ]
            },
            "minItems": 1
        },
        "roomrates": {
            "type": "array",
            "description": "A list of room rates",
            "items": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "room": {
                        "type": "string"
                    },
                    "rate": {
                        "type": "string"
                    },
                    "base": {
                        "type": "number"
                    },
                    "average": {
                        "type": "number"
                    },
                    "total": {
                        "type": "number"
                    },
                    "currency": {
                        "type": "string"
                    },
                    "ratechange": {
                        "type": "boolean"
                    },
                    "packages": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "code",
                                "name"
                            ]
                        },
                        "minItems": 1
                    }
                },
                "required": [
                    "code",
                    "room",
                    "rate",
                    "base",
                    "average",
                    "total",
                    "currency",
                    "ratechange"
                ]
            },
            "minItems": 1
        }
    },
    "required": [
        "arrival",
        "departure",
        "nights",
        "roomallocation",
        "guestcounts",
        "property",
        "propertyname",
        "available"
    ]
}

=== boSun007/myTest/json/roomAvailablilityCheck/response/json.json
{
    "property": "00001",
    "propertyname": "The Test Hotel",
    "arrival": "2015-08-09T00:00:00+02:00",
    "departure": "2015-08-12T00:00:00+02:00",
    "nights": 3,
    "guestcounts": [
        {
            "code": 10,
            "count": 2
        },
        {
            "code": 8,
            "count": 1
        }
    ],
    "roomallocation": 1,
    "available": true,
    "rates": [
        {
            "code": "BAR",
            "name": "Best Available Rate",
            "description": "Dinner, Bed & Breakfast",
            "depositrequired": true,
            "cancel": {
                "date": "2013-08-09T10:00:00+02:00"
            },
            "deposit": {
                "date": "2015-06-18T10:00:00+02:00",
                "amount": 3200
            },
            "category": "BB"
        },
        {
            "code": "S1G1",
            "name": "Stay 3 Pay 2",
            "cancel": {
                "date": "2013-08-09T10:00:00+02:00"
            }
        }
    ],
    "rooms": [
        {
            "code": "SUIT",
            "name": "Suites",
            "availability": 27
        },
        {
            "code": "EXEN",
            "name": "Executive Room Smoking",
            "availability": 4
        }
    ],
    "roomrates": [
        {
            "code": "SUIT__BAR",
            "room": "SUIT",
            "rate": "BAR",
            "base": 3365,
            "average": 3365,
            "total": 10095,
            "currency": "ZAR",
            "ratechange": false,
            "packages": [
                {
                    "code": "BRK",
                    "name": "Breakfast Inclusive"
                },
                {
                    "code": "PAR",
                    "name": "Overnight Parking"
                },
                {
                    "code": "TRF",
                    "name": "Travel Agent Fee"
                }
            ]
        },
        {
            "code": "EXEN__BAR",
            "room": "EXEN",
            "rate": "BAR",
            "base": 3115,
            "average": 3115,
            "total": 9345,
            "currency": "ZAR",
            "ratechange": false,
            "packages": [
                {
                    "code": "TRF",
                    "name": "Travel Agent Fee"
                },
                {
                    "code": "PAR",
                    "name": "Overnight Parking"
                },
                {
                    "code": "BRK",
                    "name": "Breakfast Inclusive"
                }
            ]
        },
        {
            "code": "EXEN__S1G1",
            "room": "EXEN",
            "rate": "S1G1",
            "base": 3750,
            "average": 2500,
            "total": 7500,
            "currency": "ZAR",
            "ratechange": true
        }
    ],
    "trace": "41fa410c-8380-43d8-b837-9be20a5c38b0"
}
